config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("products/", include("products.urls", namespace="products")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = []

users/urls.py
from django.urls import path
from users import views


app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
]

templates/partials/footer.html
<footer>
    &copy; KREAM Corp.
</footer>

templates/partials/header.html
<header class="px-4 h-24 bg-white w-full">
    <div class="flex justify-end items-center py-1 gap-4">
        <a href="#" class="text-gray-600">고객센터</a>
        <a href="#" class="text-gray-600">관심상품</a>
        <a href="#" class="text-gray-600">마이페이지</a>
        {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}">로그아웃</a>
        {% else %}
        <a href="{% url 'users:login' %}" class="text-gray-600">로그인</a>
        {% endif %}
    </div>
    <div></div>
</header>